In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [2]:
dataset = pd.read_csv(r"C:\Users\suraj\Downloads\dataset\salaries.csv")
dataset

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:

X  = dataset.iloc[:,0:3].values
y = dataset.iloc[:,3].values

labelencoder_X = LabelEncoder()


In [4]:
X

array([['google', 'sales executive', 'bachelors'],
       ['google', 'sales executive', 'masters'],
       ['google', 'business manager', 'bachelors'],
       ['google', 'business manager', 'masters'],
       ['google', 'computer programmer', 'bachelors'],
       ['google', 'computer programmer', 'masters'],
       ['abc pharma', 'sales executive', 'masters'],
       ['abc pharma', 'computer programmer', 'bachelors'],
       ['abc pharma', 'business manager', 'bachelors'],
       ['abc pharma', 'business manager', 'masters'],
       ['facebook', 'sales executive', 'bachelors'],
       ['facebook', 'sales executive', 'masters'],
       ['facebook', 'business manager', 'bachelors'],
       ['facebook', 'business manager', 'masters'],
       ['facebook', 'computer programmer', 'bachelors'],
       ['facebook', 'computer programmer', 'masters']], dtype=object)

In [5]:
for i in range(0,3):
    X[:,i] = labelencoder_X.fit_transform(X[:,i])
X

array([[2, 2, 0],
       [2, 2, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 1, 0],
       [2, 1, 1],
       [0, 2, 1],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 2, 0],
       [1, 2, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]], dtype=object)

In [6]:
from sklearn.compose import make_column_transformer
columntransform = make_column_transformer((OneHotEncoder(categories = 'auto'),[0,1]),remainder = "passthrough")
X = columntransform.fit_transform(X)
print(X)

[[0.0 0.0 1.0 0.0 0.0 1.0 0]
 [0.0 0.0 1.0 0.0 0.0 1.0 1]
 [0.0 0.0 1.0 1.0 0.0 0.0 0]
 [0.0 0.0 1.0 1.0 0.0 0.0 1]
 [0.0 0.0 1.0 0.0 1.0 0.0 0]
 [0.0 0.0 1.0 0.0 1.0 0.0 1]
 [1.0 0.0 0.0 0.0 0.0 1.0 1]
 [1.0 0.0 0.0 0.0 1.0 0.0 0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1]
 [0.0 1.0 0.0 0.0 0.0 1.0 0]
 [0.0 1.0 0.0 0.0 0.0 1.0 1]
 [0.0 1.0 0.0 1.0 0.0 0.0 0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1]
 [0.0 1.0 0.0 0.0 1.0 0.0 0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1]]


In [7]:
# Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 100)
print(X_train)

[[1.0 0.0 0.0 0.0 0.0 1.0 1]
 [0.0 1.0 0.0 0.0 1.0 0.0 0]
 [0.0 0.0 1.0 0.0 1.0 0.0 1]
 [0.0 0.0 1.0 1.0 0.0 0.0 0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0]
 [0.0 1.0 0.0 1.0 0.0 0.0 0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0]
 [0.0 0.0 1.0 1.0 0.0 0.0 1]
 [0.0 1.0 0.0 0.0 1.0 0.0 1]
 [1.0 0.0 0.0 1.0 0.0 0.0 0]]


In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred = regressor.predict(X_test)
print(y_pred,"\n",y_test)


[1.46551724 0.57758621 0.43103448 0.45689655 0.8362069 ] /n [1 1 1 0 1]


In [10]:
regressor.coef_

array([-0.46551724,  0.42241379,  0.04310345,  0.30747126,  0.01436782,
       -0.32183908,  0.40517241])

In [11]:
from sklearn import metrics
metrics.mean_squared_error(y_test,y_pred)

0.1908888228299644

In [12]:
a = metrics.r2_score(y_test,y_pred)
a

-0.19305514268727753

In [13]:
regressor.predict([[0,0,1,0,0,1,1]])

array([0.45689655])

In [22]:
y_train.shape

(11,)