In [27]:
import pandas as pd
import numpy as np
import math
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [28]:
dataset = pd.read_csv(r"C:\Users\suraj\Downloads\dataset\salaries.csv")
X  = dataset.iloc[:,0:3].values
y = dataset.iloc[:,3].values

labelencoder_X = LabelEncoder()

In [29]:
print(X,"\n",y)

[['google' 'sales executive' 'bachelors']
 ['google' 'sales executive' 'masters']
 ['google' 'business manager' 'bachelors']
 ['google' 'business manager' 'masters']
 ['google' 'computer programmer' 'bachelors']
 ['google' 'computer programmer' 'masters']
 ['abc pharma' 'sales executive' 'masters']
 ['abc pharma' 'computer programmer' 'bachelors']
 ['abc pharma' 'business manager' 'bachelors']
 ['abc pharma' 'business manager' 'masters']
 ['facebook' 'sales executive' 'bachelors']
 ['facebook' 'sales executive' 'masters']
 ['facebook' 'business manager' 'bachelors']
 ['facebook' 'business manager' 'masters']
 ['facebook' 'computer programmer' 'bachelors']
 ['facebook' 'computer programmer' 'masters']] 
 [0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1]


In [30]:
for i in range(0,3):
    X[:,i] = labelencoder_X.fit_transform(X[:,i])
X

array([[2, 2, 0],
       [2, 2, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 1, 0],
       [2, 1, 1],
       [0, 2, 1],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 2, 0],
       [1, 2, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]], dtype=object)

In [33]:
from sklearn.compose import make_column_transformer
columntransform = make_column_transformer((OneHotEncoder(categories = 'auto',drop = 'first'),[0,1]),remainder = "passthrough")
X = columntransform.fit_transform(X)
print(X)

[[0.0 1.0 0.0 1.0 0]
 [0.0 1.0 0.0 1.0 1]
 [0.0 1.0 0.0 0.0 0]
 [0.0 1.0 0.0 0.0 1]
 [0.0 1.0 1.0 0.0 0]
 [0.0 1.0 1.0 0.0 1]
 [0.0 0.0 0.0 1.0 1]
 [0.0 0.0 1.0 0.0 0]
 [0.0 0.0 0.0 0.0 0]
 [0.0 0.0 0.0 0.0 1]
 [1.0 0.0 0.0 1.0 0]
 [1.0 0.0 0.0 1.0 1]
 [1.0 0.0 0.0 0.0 0]
 [1.0 0.0 0.0 0.0 1]
 [1.0 0.0 1.0 0.0 0]
 [1.0 0.0 1.0 0.0 1]]


In [34]:
# Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 100)
print(X_train)

[[0.0 0.0 0.0 1.0 1]
 [1.0 0.0 1.0 0.0 0]
 [0.0 1.0 1.0 0.0 1]
 [0.0 1.0 0.0 0.0 0]
 [0.0 1.0 1.0 0.0 0]
 [0.0 1.0 0.0 1.0 0]
 [1.0 0.0 0.0 0.0 0]
 [0.0 0.0 1.0 0.0 0]
 [0.0 1.0 0.0 0.0 1]
 [1.0 0.0 1.0 0.0 1]
 [0.0 0.0 0.0 0.0 0]]


In [35]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [36]:
def convert(x):
    if x>=0.5:
        return 1
    else:
        return 0


In [37]:
y_pred = regressor.predict(X_test)
y_pred = pd.DataFrame(y_pred)
y_pred

0
0  1.465517
1  0.577586
2  0.431034
3  0.456897
4  0.836207

In [38]:
y_pred = y_pred.applymap(convert)
y_pred

0
0  1
1  1
2  0
3  0
4  1

In [39]:
regressor.coef_

array([ 0.88793103,  0.50862069, -0.29310345, -0.62931034,  0.40517241])

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8

In [41]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1, 0],
       [1, 3]], dtype=int64)

In [43]:
# Through logistic regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [44]:
lr.fit(X_train,y_train)

LogisticRegression()

In [45]:
lr_pred = lr.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,lr_pred)

array([[1, 0],
       [1, 3]], dtype=int64)